app.py
from flask import Flask
from routes import pages
import os,json
from pymongo import MongoClient
from dotenv import load_dotenv



def create_app():
	app=Flask(__name__)
	app.secret_key='SpwEY4cQhH9DwM4bqfX5fOJOyNTR-vgz4DhMxXDe-I4'
	# with open("config.json") as conf:
	# 	params=json.load(conf)["params"]
	load_dotenv()
	db_uri=os.getenv("MONGODB_URI")
	# db_conn=params["db_uri"]
	client= MongoClient(db_uri)
	app.db=client.habitrack

	app.register_blueprint(pages)
	app.jinja_env.lstrip_blocks = True
	app.jinja_env.trim_blocks = True
	return app

routes.py
from flask import (
	render_template,
	request,
	redirect,
	url_for,
	Blueprint,
	current_app,
	session,
	abort,
	flash
	)
import datetime,uuid,functools
from passlib.hash import pbkdf2_sha256
# from collections import defaultdict
 

# with open("config.json") as conf:
# 	params=json.load(conf)["params"]
# db_conn=params["connection_string"]


# app=Flask(__name__)

pages = Blueprint('habits',__name__,template_folder='templates',static_folder='static')

# client= MongoClient(db_conn)
# app.db=client.flask_blog  #client.collection/table name


# Udemyflask

'''
tasks = [
			("getmilk",False),
			("takemedicine",True)
		]
'''
# my_habits =[ "Reduce Phone","Manage Time" ]


# completed_tasks= defaultdict(list)

users={}

def today_at_midnight():
	today= datetime.datetime.today()
	return datetime.datetime(today.year,today.month,today.day)


def login_required(route):
	@functools.wraps(route)
	def route_wrapper(*args,**kwargs):
		if not session.get("email"):
			return redirect(url_for('habits.login'))
		return route(*args,**kwargs)
	return route_wrapper


# def admin_name():
# 	return "Somesh"


def date_range(start: datetime.date):
	dates =[start + datetime.timedelta(days=diff) for diff in range(-3,4)]
	return dates

@pages.context_processor
def date_range_func():
	return dict(date_range=date_range)



@pages.route('/post-details/<int:pid>')
def post_details(pid):
	return render_template('single_post.html')


@pages.route('/todo-details/<string:todo>/')
def single_todo(todo:str):
	for text,completed in tasks:
		if text == todo:
			completed_text = "[x]" if completed else "[]"
			title = f"{completed_text} - todos"
			return render_template('about.html',text=todo,completed=completed,title=title)
	else:
		# print("gotcha")
		return render_template('about.html',text=todo,title="Not found")


@pages.route('/')
@login_required
def list_habit():
	date_str = request.args.get("date")
	if date_str:
		selected_date = datetime.datetime.fromisoformat(date_str)
	else:
		selected_date = today_at_midnight()

	habit_on_date = current_app.db.habits.find({'added':{"$lte":selected_date}})

	completed_tasks =[ 
		habit["habit"] for habit in current_app.db.completions.find({"date":selected_date})
	]
	return render_template('habit_index.html',
		all_habits=habit_on_date,
		page_title="Habitat",
		selected_date=selected_date,
		completed_tasks=completed_tasks,
		email=session.get('email')
		)

@pages.route('/add-habit/',methods=["GET","POST"])
def add_habit():
	today = today_at_midnight()
	if request.method == "POST":
		new_habit = request.form.get("habit")
		# habits.append(new_habit)
		current_app.db.habits.insert_one({'_id':uuid.uuid4().hex,'added':today,'name':new_habit})
	return render_template('add_habit.html',page_title="New Habit",
		selected_date=today)


@pages.route('/complete/',methods=["POST"])
def mark_complete_task():
	date_str=request.form.get("date")
	habit = request.form.get("habitid")
	date_mod = datetime.datetime.fromisoformat(date_str)
	# completed_tasks[date_mod].append(habit)
	# print(completed_tasks)
	current_app.db.completions.insert_one({'date':date_mod,'habit':habit})
	return redirect(url_for("habits.list_habit",date=date_mod))



@pages.route("/login/",methods=["GET","POST"])
def login():
	if request.method=="POST":
		email = request.form["email"]
		password = request.form["password"]
		if email and password and users.get(email):
			if pbkdf2_sha256.verify(password,users.get(email)):
				session['email'] = email
				flash("Login Successfull")
				return redirect(url_for('habits.list_habit'))
		flash("Incorrect email or passowrd.")
	
	return render_template('login.html')

@pages.get("/protected")
def protected():
	if not session.get("email"):
		return redirect(url_for('habits.login'))
	return render_template("protected.html")

@pages.route("/signup/",methods=["GET","POST"])
def signup():
	if request.method=="POST":
		email = request.form["email"]
		password = request.form['password']
		users[email] = pbkdf2_sha256.hash(password) 
		flash("Successfully Signed Up")
		return redirect(url_for('habits.login'))
	return render_template("signup.html")

@pages.route('/logout/')
def log_out():
	if session.get('email'):
		session.clear()
		flash("Logout Successfull")
		return redirect(url_for('habits.login'))
	else:
		return redirect(url_for('habits.index'))

# @app.route('/mypage')
# def my_page():
# 	return "mypage"

# if __name__ == '__main__':
# 	app.run(debug=True)

templates/add_habit.html
{% extends 'base.html'%}

{% block main_content %}
	
	<form method="POST" action="" class="form">
		<label for="habit_usr" class="form_label">Enter your habits</label>
<textarea class="form_input" name="habit" id="habit_usr" rows="3" placeholder="Enter your habit for tracking"></textarea>
	<button type="submit" class="form_btn">Add</button>
	</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{{page_title or "Habi-tracker"}}</title>
	
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='style.css')}}">
	{% block head %}
	{% endblock %}
	
</head>
<body>
	<header class="header">
		<h1 class="header_logo">
			<a class="header_link" href="{{ url_for('habits.list_habit') }}">Habi-tracker</a>
		</h1>
			{% if "add" not in request.endpoint %}
				<a class="header_link" href="{{ url_for('habits.add_habit') }}">+ Add</a>
			{% else %}
			{% endif %}
			{% if email %}
				<p class="header_link"> Hi {{email}}, Welcome </p>
			{% else %}
			{% endif %}

			{% if "add" not in request.endpoint %}
				<a class="header_link" href="{{ url_for('habits.log_out') }}">Logout</a>
			{% else %}
			{% endif %}
		
	</header>
	{% for message in get_flashed_messages() %}
	<div class="alert">
		<p>{{message}}</p>
	</div>
	{% endfor %}
	<main class="main">
		<section class="dates">
			{% for date in date_range(selected_date) %}
				<a class="date_link {{ 'dates_link-current' if loop.index0==3 else '' }}" href=" {{ url_for('habits.list_habit',date=date) }} ">
						<time class="date" datetime=" {{date}} ">
							<span>{{date.strftime("%a")}}</span>
							<span>{{date.strftime("%d")}}</span>
						</time>
				</a>
			{% endfor %}
	</section>
		{% block main_content %}
		{% endblock %}
	</main>
</body>
</html>

templates/habit_index.html
{% extends 'base.html' %}

{% block main_content%}
		
	

	<section class="habit_list">
		
		{% for habit in all_habits %}
				
			{% set completed = habit['_id'] in completed_tasks %}
			{% if completed %}

				<div class="habit completed">
					<p class="habit_name">
						{{ loop.index }}. {{ habit["name"] }}
					</p>
					<svg class="habit__icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
+                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
+                </svg>
				</div>
				{% else %}
					<div class="habit">
						<form method="POST" class="habit_form" action="{{ url_for('habits.mark_complete_task') }}">
							<input type="hidden" name="habitid" value="{{ habit['_id'] }}">
							<input type="hidden" name="date" value="{{ selected_date }}">
							<button type="submit" class="habit_button">{{habit["name"]}}</button>
						</form>
					</div>
			{% endif %}

		{% endfor %}	
		
		
	</section>
{% endblock %}



	

templates/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Habit Tracker | Login</title>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='login.css') }}">
</head>
<body>
	
<!-- <h1>Welcome, this is login page</h1> -->
{% for message in get_flashed_messages() %}
	<div class="alert">
		<p>{{message}}</p>
	</div>
	{% endfor %}

	<main>
		<div class="login-container">
			<div class="login-box">
				<h2>Login</h2>
					<form method="POST">
						<label for="mail">E-mail</label>
						<input type="email" name="email" placeholder="Enter E-mail"  id ="mail" required />
					
						<label for="pass"> Password</label>
						<input type="password" name="password"  placeholder="Enter Password" id="pass" required />
					
						<input type="submit" class="button" value="Login">
					</form>		
			</div>
		</div>
		
		<p class="extra"><a href="{{url_for('habits.signup')}}">Sign-up</a> Instead?</p>
	</main>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Habit Tracker | Sign Up</title>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='login.css') }}">
</head>
<body>
	<!-- <h1>Welcome,this is signup page</h1> -->
	<main>
	<div class="login-container">
		<div class="login-box">
			<h2>Sign Up</h2>
			<form method="POST">
				<label for="mail">E-mail</label>
				<input type="email" name="email" id="mail" required />
			
				<label for="pass">Password </label>
				<input type="password" name="password" id="pass" required />
			
				<input type="submit" class="button" value="Sign Up">
			</form>
		</div>	
	</div>
	<p class="extra"><a href="{{url_for('habits.login')}}">Login</a> Instead ?</p>
	<main></main>
</body>
</html>